# Generated by Django 5.0.6 on 2024-05-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matosrendu',
            name='agentsAyantretour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.listeemploye'),
        ),
    ]
